name: pa11y tests

on:
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/ci-frontend-a11y.yml

defaults:
  run:
    working-directory: ./frontend

env:
  NODE_VERSION: 20
  LOCKFILE_PATH: ./frontend/package-lock.json
  PACKAGE_MANAGER: npm

jobs:
  build:
    name: Pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: ${{ env.LOCKFILE_PATH }}
          cache: ${{ env.PACKAGE_MANAGER }}

      - name: Install dependencies
        run: npm ci

      - name: Create screenshots directory
        run: mkdir -p screenshots-output

      - name: Build project
        run: npm run build

      - name: Start server
        run: npm run start &

      - name: Wait for server to be ready
        run: |
          # Ensure the server wait script is executable
          chmod +x ./bin/wait-for-frontend.sh
          ./bin/wait-for-frontend.sh
        shell: bash

      - name: Check server health
        run: |
          echo "Waiting for server to be ready..."
          sleep 10
          curl -I http://localhost:3000

      - name: Run pa11y-ci
        run: |
          npm run test:pa11y 2>&1 | tee pa11y-debug.log
        env:
          DEBUG: 'pa11y*'
        shell: bash

      - name: List files in working directory
        run: ls -la
        shell: bash

      - name: List files in current directory
        run: ls -la .
        shell: bash

      - name: Force fail to test artifact upload
        run: exit 1
        if: always()

      - name: Upload Pa11y debug log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: pa11y-debug-log
          path: pa11y-debug.log
